INSERT INTO public.focuspoint_mail_content (id, url, dyk1_url, dyk1_tekst, dyk2_url, dyk2_tekst, dyk3_url, dyk3_tekst, imageurl, snc1_url, snc1_imageurl, snc1_tekst, snc2_url, snc2_imageurl, snc2_tekst, snc3_url, snc3_imageurl, snc3_tekst, text, title) VALUES (1, 'https://www.shepardlawpllc.com/shepard-blog/financial-fitness-what-does-it-mean-to-be-financially-fit', 'https://www.araglegal.com/member/learning-center/topics/budget-and-finance/nine-ways-get-financially-fit', '9 tips to be Financial Fit', 'https://www.ourgrovecu.com/the-importance-of-being-financially-fit/', 'Importance of Financial Fit', 'https://www.wealthcontrol.com/what-does-it-mean-to-be-financially-fit', 'What does it mean to be financial fit?', 'https://drive.google.com/uc?export=download&id=1HGeioh4g2FrBSLEJCv488_JhwqrS9BuH', 'https://www.consumerscu.org/blog/how-to-improve-your-financial-fitness', 'https://drive.google.com/uc?export=download&id=1FIiXTuLp6BRhQANO-on6fXt0KXmqOulY', 'Improve Financial Fitness', 'https://fcaa.org/2024/01/07/tips-to-get-financially-fit/', 'https://drive.google.com/uc?export=download&id=12xQwcEfXXBE3mTeMfUZNaqZrit_lQDhV', '5 tips for Financial Fitness', 'https://spero.financial/7-ways-to-stop-wasting-money-on-things-you-dont-want/', 'https://drive.google.com/uc?export=download&id=1HqvMIh8yysfvKiBg_MudE7FpQRfFcU_b', 'Stop wasting money', 'Niet zeker wat Financial Fit betekent? In deze content kom je er meer over te weten.', 'Financial Fit');
INSERT INTO public.focuspoint_mail_content (id, url, dyk1_url, dyk1_tekst, dyk2_url, dyk2_tekst, dyk3_url, dyk3_tekst, imageurl, snc1_url, snc1_imageurl, snc1_tekst, snc2_url, snc2_imageurl, snc2_tekst, snc3_url, snc3_imageurl, snc3_tekst, text, title) VALUES (4, 'https://your.yale.edu/learn-and-grow-what-adaptability-workplace', 'https://asana.com/nl/resources/workplace-adaptability-skills', '6 tips to increase adaptability ', 'https://www.indeed.com/career-advice/career-development/adaptability-in-the-workplace', 'importance of adaptability', 'https://www.clevry.com/en/blog/adaptability-soft-skills/', 'Adaptability soft skills', 'https://drive.google.com/uc?export=download&id=1qyMHk8IyEmLKHwFw5i9lrhsOEn6CJbNf', 'https://www.rtl.nl/sponsored-special/artikel/4261666/creativiteit-op-de-werkvloer-5-tips', e'https://drive.google.com/uc?
export=download&id=1rSprHG5D2492HXXjsFlIncxWI1wyZczs
', '5 tips voor creativiteit op de werkvloer', 'https://beeliners.nl/blog/tips-innoveren/', e'https://drive.google.com/uc?
export=download&id=1rdvIMfguNqHeLmW7vyqobtdBMgyuvCOP', '7 tips om je meer te innoveren', 'https://carinasampers.nl/zelfleiderschap/vijf-tips-voor-meer-wendbaarheid/', e'https://drive.google.com/uc?
export=download&id=1rezlF56Ol0HTekYd6V-asFgx79MBxwCS', '5 tips voor meer wendbaarheid', 'Niet zeker wat Adaptability betekent? In deze content kom je er meer over te weten.', 'Adaptability');
INSERT INTO public.focuspoint_mail_content (id, url, dyk1_url, dyk1_tekst, dyk2_url, dyk2_tekst, dyk3_url, dyk3_tekst, imageurl, snc1_url, snc1_imageurl, snc1_tekst, snc2_url, snc2_imageurl, snc2_tekst, snc3_url, snc3_imageurl, snc3_tekst, text, title) VALUES (3, 'https://www.desteven.nl/persoonlijke-ontwikkeling/assertiviteit/zelfbewust', 'https://feedforwardanalyse.nl/artikel/hoe-je-zelf-bewustzijn-vergroten/', 'hoe vergoot ik mijn zelfbewustzijn?', 'https://www.avogel.nl/blog/eigenwaarde-versterken-zo-doe-je-dat-met-deze-10-tips/', '10 tips om Me Value te vergroten', 'https://psycholoog.nl/blogs/het-belang-van-eigenwaarde-en-zelfrespect-de-kern-van-persoonlijke-groei/#:~:text=Je%20kunt%20jezelf%20omarmen%2C%20ondanks,kan%20stellen%20in%20je%20relaties.', 'het belang van Me Value', e'
https://drive.google.com/uc?export=download&id=1jg526qZDH9Bbwe5kP3vYPFFPuctcaeh8
', 'https://nl.indeed.com/carrieregids/ontwikkeling/zelfkennis-ontwikkelen', 'https://drive.google.com/uc?export=download&id=1rJO58T4I2UoDHR0pawtslgc-7-q8nfYZ', 'Het belang van zelfkennis', 'https://www.forbes.com/sites/carolinecastrillon/2023/10/15/10-secrets-to-boost-your-confidence-in-the-workplace/', 'https://drive.google.com/uc?export=download&id=1jg526qZDH9Bbwe5kP3vYPFFPuctcaeh8', 'How to improve confidence in workplace', 'https://parvaizyousuf.medium.com/how-to-improve-knowledge-and-skills-at-work-top-14-ways-975b5e9a991d', e'https://drive.google.com/uc?
export=download&id=1rPijIj77Tpw-YWlwyqYSy29YyaiOkH8o
', '14 tips om kennis en vaardigheden te verbeteren', 'Niet zeker wat Me Value betekent? In deze content kom je er meer over te weten.', 'Me Value');
INSERT INTO public.focuspoint_mail_content (id, url, dyk1_url, dyk1_tekst, dyk2_url, dyk2_tekst, dyk3_url, dyk3_tekst, imageurl, snc1_url, snc1_imageurl, snc1_tekst, snc2_url, snc2_imageurl, snc2_tekst, snc3_url, snc3_imageurl, snc3_tekst, text, title) VALUES (2, 'https://boommanagement.nl/artikel/wat-is-job-crafting/', 'https://tailoredthinking.co.uk/blog/2020/5/12/different-types-of-job-crafting', 'Types of Job Crafting', 'https://sdf.ac.uk/12772/why-does-job-crafting-matter#:~:text=Job%20crafting%20enables%20people%20to,buffering%20stress%20and%20boosting%20wellbeing.', 'Why does it matter?', 'https://www.forbes.com/sites/drnancydoyle/2024/02/20/four-tips-for-job-crafting-a-tool-for-neuroinclusion/', '4 tips for Job Crafting', 'https://drive.google.com/uc?export=download&id=1aTkk0gmxYI3t49-L0sbM1JnPh781i15P', 'https://www.reiswerk.nl/nieuws/7-tips-om-te-netwerken-op-de-werkvloer', 'https://drive.google.com/uc?export=download&id=1r1aqF4vEk4hDwi77xRE2lx1YUDbqDR2t', '7 tips om netwerken op werkvloer te verbeteren', 'https://rhwitteveen.nl/timemanagement-10-tips-om-je-werk-op-orde-te-brengen/', 'https://drive.google.com/uc?export=download&id=1Z9D81v4JKUYPeQnGVrEtdsGbNVB3i2XU ', 'Krijg je werk op orde', 'https://defittemedewerker.nl/balans-werk-en-prive/', 'https://drive.google.com/uc?export=download&id=1r8JVEZqh66Rt77uWezAYWy3-Gfwdr0qz', '6 tips voor werk/prive balans', 'Niet zeker wat Job Crafting betekent? In deze content kom je er meer over te weten.', 'Job Crafting');
